name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: Publish
        run: |
          yarn config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          yarn publish --non-interactive --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
   